# Generated by Django 4.1.5 on 2023-01-19 20:02

from django.db import migrations, models
import timmy_mountains.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000, validators=[timmy_mountains.models.is_mountain])),
            ],
        ),
        migrations.CreateModel(
            name='MountainWithTunnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000, validators=[timmy_mountains.models.is_mountain_with_tunnels])),
            ],
        ),
    ]
